### ISSUE TITLE
自适应列宽

### ISSUE THREAD

**Issue by ddkwork** [hujun-open/dvlist#1]
你好，
1 列宽如何自适应内容长度
2 如何全选列并右键复制或者按下复制整列，每列的单个元素如何右键拓展解码功能
小弟想弄一个Charles抓包工具的界面，依您的葫芦画了瓢遇到这些问题特向您请教

![Screenshot_20211201_215841_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/144248518-a6689f28-dc30-4994-9bcb-893c296e1e24.jpg)

**Comment by ddkwork** [comment]
排序每列的话，小弟研究了下倒是方便实现，只是过滤功能的话，要么过滤一列或者全部列，那么传递field index好像不妥，假设像Charles一样勾选过滤某几列的话，
那么得把每列都填充到各自的切片，其他的接口都很不错，过滤签名可否加入：返回每列切片的实现呢

**Comment by ddkwork** [comment]
对于列宽的调整我的思路是：取标题文本和列文本，谁最长就更改列宽为最大值，如果太长大于预定一个max，则改为上一次的最大宽度，如果无法拖动列显示全部，那么提供右键复制功能，可惜我写不出来，望大湿抽空拓展一波喔

**Comment by hujun-open** [comment]
没想到还有人找到这个，   这个是我之前为了 golitebook 写的， 后来发现fyne对于中文输入法支持[有问题](https://github.com/fyne-io/fyne/issues/618)，而且那个问题是上游glfw的问题，目前根本没有计划解决，就没想继续花时间在fyne上了。 
我建议你也换一个更成熟的gui，比如qt

**Comment by ddkwork** [comment]
> 没想到还有人找到这个， 这个是我之前为了 golitebook 写的， 后来发现fyne对于中文输入法支持[有问题](https://github.com/fyne-io/fyne/issues/618)，而且那个问题是上游glfw的问题，目前根本没有计划解决，就没想继续花时间在fyne上了。 我建议你也换一个更成熟的gui，比如qt

qt已经试水，无法调试啊，apk也编译不了

**Comment by ddkwork** [comment]
全网唯一动态填充表功能的只有您这个喔，老师

**Comment by hujun-open** [comment]
像我之前说的，fyne目前不是个成熟的gui，我不打算为它花时间了
